const config = {
  ENVIRONMENT: process.env.NODE_ENV,
  JSONPLACEHOLDER_API_BASE_URL: process.env.JSONPLACEHOLDER_API_BASE_URL,
  JSONPLACEHOLDER_ALBUM_ID: process.env.JSONPLACEHOLDER_ALBUM_ID
};

export default config;
